build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-N/A
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: pre-commit
  commands: pre-commit run -a
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openstack-k8s-operators
  repo: edpm-image-builder
